.PHONY: clean All

All:
	@echo "----------Building project:[ 03abstract - Debug ]----------"
	@cd "03abstract" && "$(MAKE)" -f  "03abstract.mk"
clean:
	@echo "----------Cleaning project:[ 03abstract - Debug ]----------"
	@cd "03abstract" && "$(MAKE)" -f  "03abstract.mk" clean
