.PHONY: clean All

All:
	@echo "----------Building project:[ 07tax_calculation - Debug ]----------"
	@cd "07tax_calculation" && "$(MAKE)" -f  "07tax_calculation.mk"
clean:
	@echo "----------Cleaning project:[ 07tax_calculation - Debug ]----------"
	@cd "07tax_calculation" && "$(MAKE)" -f  "07tax_calculation.mk" clean
