.PHONY: clean All

All:
	@echo "----------Building project:[ sintheta - Debug ]----------"
	@cd "sintheta" && "$(MAKE)" -f  "sintheta.mk"
clean:
	@echo "----------Cleaning project:[ sintheta - Debug ]----------"
	@cd "sintheta" && "$(MAKE)" -f  "sintheta.mk" clean
