.PHONY: clean All

All:
	@echo "----------Building project:[ 05copy_move_constr - Debug ]----------"
	@cd "05copy_move_constr" && "$(MAKE)" -f  "05copy_move_constr.mk"
clean:
	@echo "----------Cleaning project:[ 05copy_move_constr - Debug ]----------"
	@cd "05copy_move_constr" && "$(MAKE)" -f  "05copy_move_constr.mk" clean
